#!/usr/bin/env python3
"""
Quality-Fabric Template Bridge
Connects Quality-Fabric validation results to MAESTRO Template Repository
"""

import asyncio
import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

from quality_fabric_client import QualityValidationResult
from templates.enterprise_template_repository.quality_integration import (
    QualityAnalysisResult,
    TemplateExtractor,
)
from templates.enterprise_template_repository.template_manager import (
    EnterpriseTemplateRepository,
    TemplateMetadata,
)
from templates.quality_to_template_transformer import (
    QualityToTemplateTransformer,
    transform_quality_result,
)

logger = logging.getLogger(__name__)


class QualityFabricTemplateBridge:
    """
    Bridge between Quality-Fabric and Template Repository
    Automatically creates templates from high-quality validated code
    """

    def __init__(
        self,
        template_repository: EnterpriseTemplateRepository = None,
        quality_threshold: float = 80.0,
    ):
        """
        Initialize the bridge

        Args:
            template_repository: Enterprise template repository instance
            quality_threshold: Minimum quality score for template creation
        """
        self.template_repository = template_repository or EnterpriseTemplateRepository()
        self.transformer = QualityToTemplateTransformer()
        self.extractor = TemplateExtractor(
            repository=self.template_repository, quality_threshold=quality_threshold
        )
        self.logger = logging.getLogger(self.__class__.__name__)

    async def process_validation_result(
        self, quality_result: QualityValidationResult, workflow_result: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Process Quality-Fabric validation result and create templates

        Args:
            quality_result: Quality validation result from Quality-Fabric
            workflow_result: Original workflow execution result

        Returns:
            Dictionary with processing results:
            {
                "templates_created": int,
                "template_ids": List[str],
                "files_processed": int,
                "skipped_files": int,
                "errors": List[str]
            }
        """
        result = {
            "templates_created": 0,
            "template_ids": [],
            "files_processed": 0,
            "skipped_files": 0,
            "errors": [],
        }

        try:
            # Check if quality is sufficient for template creation
            if not self.transformer.should_create_template(quality_result):
                self.logger.info("Quality insufficient for template creation")
                return result

            # Get files generated by workflow
            files_generated = workflow_result.get("files_generated", [])
            project_path = workflow_result.get("project_path", "")

            if not files_generated:
                self.logger.warning("No files generated in workflow")
                return result

            self.logger.info(f"Processing {len(files_generated)} files for template extraction")

            # Process each file
            for file_path in files_generated:
                try:
                    result["files_processed"] += 1

                    # Convert to absolute path if needed
                    if not Path(file_path).is_absolute() and project_path:
                        full_path = Path(project_path) / file_path
                    else:
                        full_path = Path(file_path)

                    # Skip non-existent files
                    if not full_path.exists():
                        self.logger.warning(f"File not found: {full_path}")
                        result["skipped_files"] += 1
                        continue

                    # Read file content
                    try:
                        with open(full_path, "r", encoding="utf-8") as f:
                            code_content = f.read()
                    except Exception as e:
                        self.logger.error(f"Failed to read {full_path}: {e}")
                        result["skipped_files"] += 1
                        result["errors"].append(f"Read error: {full_path}: {e}")
                        continue

                    # Transform quality result to QualityAnalysisResult format
                    analysis_result = self._transform_to_analysis_result(
                        quality_result, str(full_path), code_content
                    )

                    # Extract templates using existing TemplateExtractor
                    template_ids = await self.extractor.process_quality_analysis_result(
                        analysis_result
                    )

                    if template_ids:
                        result["templates_created"] += len(template_ids)
                        result["template_ids"].extend(template_ids)
                        self.logger.info(
                            f"✅ Created {len(template_ids)} template(s) from {full_path.name}"
                        )
                    else:
                        result["skipped_files"] += 1

                except Exception as e:
                    self.logger.error(f"Error processing file {file_path}: {e}")
                    result["errors"].append(f"Processing error: {file_path}: {e}")
                    result["skipped_files"] += 1

            # Log summary
            self.logger.info(
                f"Template extraction complete: "
                f"{result['templates_created']} templates created, "
                f"{result['files_processed']} files processed, "
                f"{result['skipped_files']} files skipped"
            )

            # Register templates with maestro-templates if any created
            if result["templates_created"] > 0:
                try:
                    from maestro_templates_integration import register_templates_to_maestro

                    # Get template metadata objects
                    template_metadata_list = []
                    for template_id in result["template_ids"]:
                        # Retrieve template from repository
                        # Note: TemplateExtractor returns template IDs, we'd need to retrieve them
                        # For now, we'll add a placeholder for maestro-templates registration
                        pass

                    # TODO: Implement template metadata retrieval and registration
                    # maestro_result = await register_templates_to_maestro(
                    #     template_metadata_list,
                    #     workflow_result
                    # )
                    # result["maestro_templates_registration"] = maestro_result

                    self.logger.info("maestro-templates integration: Ready for implementation")

                except Exception as maestro_error:
                    self.logger.warning(f"maestro-templates registration skipped: {maestro_error}")
                    result["maestro_templates_error"] = str(maestro_error)

        except Exception as e:
            self.logger.error(f"Fatal error in template bridge: {e}")
            result["errors"].append(f"Fatal error: {e}")

        return result

    def _transform_to_analysis_result(
        self, quality_result: QualityValidationResult, file_path: str, code_content: str
    ) -> QualityAnalysisResult:
        """
        Transform Quality-Fabric result to QualityAnalysisResult format

        Args:
            quality_result: Quality validation result from Quality-Fabric
            file_path: Path to the file
            code_content: File content

        Returns:
            QualityAnalysisResult compatible with TemplateExtractor
        """
        # Determine language from file extension
        path = Path(file_path)
        ext_to_lang = {
            ".py": "python",
            ".js": "javascript",
            ".ts": "typescript",
            ".jsx": "javascript",
            ".tsx": "typescript",
            ".java": "java",
            ".go": "go",
            ".rs": "rust",
        }
        language = ext_to_lang.get(path.suffix, "unknown")

        # Extract issues from quality result
        issues = quality_result.issues if quality_result.issues else []

        # Build metrics dictionary
        metrics = {
            "quality_score": quality_result.quality_score,
            "security_score": quality_result.security_score,
            "performance_score": quality_result.performance_score,
            "maintainability_score": quality_result.maintainability_score,
            "test_coverage": quality_result.test_coverage,
            "total_tests": quality_result.total_tests,
            "passed_tests": quality_result.passed_tests,
            "failed_tests": quality_result.failed_tests,
            "error_tests": quality_result.error_tests,
            "duration": quality_result.duration,
        }

        return QualityAnalysisResult(
            file_path=file_path,
            language=language,
            quality_score=quality_result.quality_score,
            security_score=int(quality_result.security_score),
            performance_score=int(quality_result.performance_score),
            maintainability_score=int(quality_result.maintainability_score),
            test_coverage=quality_result.test_coverage,
            issues=issues,
            metrics=metrics,
            code_content=code_content,
        )

    async def create_templates_from_workflow(
        self, workflow_result: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Convenience method to create templates directly from workflow result
        Assumes quality_validation key exists in workflow_result

        Args:
            workflow_result: Workflow execution result with quality_validation

        Returns:
            Template creation result dictionary
        """
        quality_data = workflow_result.get("quality_validation")

        if not quality_data:
            self.logger.warning("No quality validation data in workflow result")
            return {
                "templates_created": 0,
                "template_ids": [],
                "files_processed": 0,
                "skipped_files": 0,
                "errors": ["No quality validation data"],
            }

        # Reconstruct QualityValidationResult from dictionary
        from quality_fabric_client import QualityValidationResult

        quality_result = QualityValidationResult(
            execution_id=quality_data.get("execution_id", "unknown"),
            success=True,
            quality_score=quality_data.get("quality_score", 0),
            security_score=quality_data.get("security_score", 0),
            performance_score=quality_data.get("performance_score", 0),
            maintainability_score=quality_data.get("maintainability_score", 0),
            test_coverage=quality_data.get("test_coverage", 0),
            total_tests=quality_data["test_results"]["total"],
            passed_tests=quality_data["test_results"]["passed"],
            failed_tests=quality_data["test_results"]["failed"],
            error_tests=quality_data["test_results"]["errors"],
            duration=quality_data.get("duration", 0),
            detailed_results={},
            recommendations=quality_data.get("recommendations", []),
            issues=quality_data.get("issues", []),
            timestamp=0,
        )

        return await self.process_validation_result(quality_result, workflow_result)


# Convenience function
async def create_templates_from_quality_validation(
    quality_result: QualityValidationResult,
    workflow_result: Dict[str, Any],
    template_repository: EnterpriseTemplateRepository = None,
) -> Dict[str, Any]:
    """
    Convenience function to create templates from quality validation

    Args:
        quality_result: Quality validation result from Quality-Fabric
        workflow_result: Original workflow execution result
        template_repository: Optional template repository instance

    Returns:
        Template creation result dictionary
    """
    bridge = QualityFabricTemplateBridge(template_repository)
    return await bridge.process_validation_result(quality_result, workflow_result)
